name: Build .NET Desktop App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore DeviceIF.sln

    - name: Build solution
      run: msbuild DeviceIF.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU"

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Binaries-${{ matrix.configuration }}
        path: bin\${{ matrix.configuration }}
