name: .NET Build with Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-analyze:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: dotnet restore DeviceIF.sln

    - name: Build solution
      run: msbuild DeviceIF.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /p:WarningLevel=4 /clp:summary

    - name: Run Code Analysis
      continue-on-error: true
      run: |
        dotnet format --verify-no-changes --severity warn --report "code-style-report.json"
        msbuild DeviceIF.sln /p:Configuration=${{ matrix.configuration }} `
          /p:RunAnalyzers=true `
          /p:AnalysisMode=AllEnabledByDefault `
          /p:WarningLevel=4 `
          /p:TreatWarningsAsErrors=false `
          /clp:"summary;errorsonly"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.configuration }}
        path: |
          bin/${{ matrix.configuration }}
          *.md
          *.json
          **/*CodeAnalysisLog.txt